"""post pic

Revision ID: 4a5e8e4abae7
Revises: 703f8cb0a193
Create Date: 2025-12-15 15:17:42.138755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5e8e4abae7'
down_revision = '703f8cb0a193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_pic', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('post_pic')

    # ### end Alembic commands ###
