"""profile pic

Revision ID: 703f8cb0a193
Revises: b238bc073346
Create Date: 2025-12-15 10:31:55.544829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703f8cb0a193'
down_revision = 'b238bc073346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
